require("prototypes.seamap")
require("prototypes.groups")
require("prototypes.burnables")
require("prototypes.intermediate")
require("prototypes.recipes")
require("prototypes.technology")
require("prototypes.mechanicalinserter")
require("prototypes.entity.ship")